
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiqqhyfksaerkvenwupw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpcXFoeWZrc2Flcmt2ZW53dXB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzIwMTQsImV4cCI6MjA2MjY0ODAxNH0.hQ9-V9IF5CN31I3VlOldgbYuujsOccMk2U5-l2CQ7f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
